#!/bin/zsh

case "$1" in
    start-fg)
        leshan >/dev/null || (cd ~/tools/leshan/leshan-server-demo && java -jar target/leshan-server-demo-1.0.0-SNAPSHOT-jar-with-dependencies.jar)
        ;;
    start)
        leshan >/dev/null || (cd ~/tools/leshan/leshan-server-demo && java -jar target/leshan-server-demo-1.0.0-SNAPSHOT-jar-with-dependencies.jar &>/dev/null &!)
        ;;
    stop)
        leshan | awk '{print $2}' | grep '^[1-9][0-9]\{0,4\}$' | xargs kill --
        ;;
    restart)
        leshan stop
        sleep 1
        leshan start
        ;;
    *)
        ps aux | grep leshan-server-demo | grep -v grep
esac
