#!/bin/sh

# Starts tcpdump on a remote host, then forwards its output to local Wireshark over SSH

if [[ ! "$1" ]]; then
    echo "usage: $0 TARGET_HOST IFACE FILTER..."
    return 1
fi

local TARGET="$1"
local IFACE="$1"
shift 2
local FILTER="$@"

ssh "$TARGET" -t "tcpdump -s0 -U -n -w - -i '$IFACE' '$FILTER'" | wireshark -k -i -
